
async function main() {
  console.log(12345)
}

main().catch(console.error)
